# 该项配置在springboot和springcloud版本不兼容时启用
#  main:
#    allow-bean-definition-overriding: true
#  datasource:
#    url:  jdbc:mysql://dbserver1:3306/emall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=15000&allowMultiQueries=true&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 10
#      maximum-pool-size: 25
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: ExpendHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
# 配置模板的后缀，自动读取spring.mvc.view.suffix
spring:
  mvc:
    view:
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.128.128:8848
# swagger2
#swagger2.package: com.vigorous.emall.portal.controller

#配置模板想到classpath路径，后面须加上"/"
#beetl:
#  templates-path: templates/
#  config:
#    html-tag-flag: true

# 广告Cid
big_ad_index: 1

